name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v3
      with:
        repository: 3DSGuy/Project_CTR
        path: Project_CTR

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        path: Thenaya

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y build-essential p7zip-full

    - name: Compile makerom
      run: |
        cd Project_CTR
        make
        cd ../
        cp Project_CTR/makerom/bin/makerom Thenaya/makerom
        chmod a+x Thenaya/makerom

    - name: Install makerom
      run: |
        cp Project_CTR/makerom/bin/makerom Thenaya/makerom
        chmod a+x Thenaya/makerom

    - name: Build Thenaya binaries
      run: |
        cd Thenaya
        make release

    - name: Retrieve commit identification
      run: |
        cd Thenaya
        GIT_BRANCH=$(git name-rev --name-only HEAD)
        echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV
        GIT_HASH=$(git rev-parse --short HEAD)
        echo "GIT_HASH=${GIT_HASH}" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3
      with:
        name: Thenaya-${{ env.GIT_HASH }}
        path: |
          Thenaya/output/Thenaya_*.zip
          Thenaya/output/Thenaya.cia

    - uses: marvinpinto/action-automatic-releases@v1.2.1
      if: github.event_name != 'pull_request'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: ${{ env.GIT_BRANCH != 'master' }}
        title: Thenaya-${{ env.GIT_HASH }}
        files: |
          Thenaya/output/Thenaya_*.zip
          Thenaya/output/Thenaya.cia
