name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: abandonedcart/devkitarm

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build Thenaya binaries
      run: make release

    - name: Retrieve commit identification
      run: |
        GIT_BRANCH=$(git name-rev --name-only HEAD)
        echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV
        GIT_HASH=$(git rev-parse --short HEAD)
        echo "GIT_HASH=${GIT_HASH}" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v4
      with:
        name: Thenaya-${{ env.GIT_HASH }}
        path: |
          output/Thenaya_*.zip
          output/Thenaya.cia

    - uses: 8bitDream/action-github-releases@v1.0.0
      if: github.event_name != 'pull_request'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: ${{ env.GIT_BRANCH != 'master' }}
        title: Thenaya-${{ env.GIT_HASH }}
        files: |
          output/Thenaya_*.zip
          output/Thenaya.cia

    - name: Discord webhook notification
      if: github.event_name != 'pull_request'
      continue-on-error: true
      uses: distributhor/workflow-webhook@v3.0.4
      env:
        webhook_type: 'json-extended'
        webhook_url: 'https://discord.com/api/webhooks/1109893889340485632/Vd-DqFhZWlfu86C8UqNxv8Z47WHm8aJC9eWZcu7ggC0lnFboeOHS9hUNdO6J2nowPsmP/github'
        data: '{ "download": "https://github.com/HiddenRamblings/Thenaya/releases/download/latest/Thenaya.cia" }'
